// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MyRecipeBook.Infraestructure.DataAcess;

#nullable disable

namespace MyRecipeBook.Infraestructure.Migrations
{
    [DbContext(typeof(MyRecipeBookDbContext))]
    [Migration("20260915000000_SetRecipeUserToNullOnDelete")]
    partial class SetRecipeUserToNullOnDelete
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
